name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install check
      run: sudo apt-get install check
    - name: make tests
      run: (cd Tests && make ubuntu=1)
    - name: make Sampling
      run: (cd Sampling && make)
    - name: make Extraction
      run: (cd Extraction && make)

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2
    - name: install check
      run: sudo apt-get install check
    - name: make tests
      run: (cd Tests && make ubuntu=1)
    - name: run tests
      run: Tests/Checks.x
