name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: make tests
      run: Tests/make
    - name: make Sampling
      run: Sampling/make
    - name: make Extraction
      run: Extraction/make
