name: C/C++ CI

on:
  push:
    branches: [ master,Workflow ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: clean apt
      run: |
        sudo apt-get clean
        sudo mv /var/lib/apt/lists /tmp
        sudo mkdir -p /var/lib/apt/lists/partial
        sudo apt-get clean
    - name: update apt
      run: sudo apt-get update
    - name: determine check version
      run: apt policy check
    - name: install check
      run: sudo apt-get install check
    - name: determine OS
      run: grep ^NAME=".*" /etc/os-release
    - name: make tests
      run: (cd Tests && make)
    - name: make Sampling
      run: (cd Sampling && make)
    - name: make Extraction
      run: (cd Extraction && make)

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2
    - name: install check
      run: sudo apt-get install check
    - name: make tests
      run: (cd Tests && make ubuntu=1)
    - name: run tests
      run: Tests/Checks.x

  macOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: install check
      run: brew install check
    - name: make tests
      run: (cd Tests && make)
    - name: make Sampling
      run: (cd Sampling && make)
    - name: make Extraction
      run: (cd Extraction && make)
